import { describe, it, expect } from 'vitest';
import PDFKitDocument from 'pdfkit';
import { Document as DocxDocument, Packer, Paragraph, TextRun } from 'docx';
import { extractPdfText } from '../../src/parsing/pdf-extractor.js';
import { extractDocxText } from '../../src/parsing/docx-extractor.js';
import { DocumentTextExtractor } from '../../src/parsing/document-text-extractor.js';
import { isOk, isErr } from '@careerpilot/domain';
import { PDF_MIME_TYPE, DOCX_MIME_TYPE } from '@careerpilot/application';

/**
 * Builds a real single-page PDF containing one line of text via `pdfkit`
 * (test-only devDependency — NOT the extraction library; that's `pdf-parse`,
 * chosen and justified in `pdf-extractor.ts`). `pdf-lib` was tried first for
 * this fixture generator and dropped: its default Flate-compressed content
 * streams use an encoding `pdf-parse`'s bundled (older) `pdf.js` fails to
 * decode ("Unknown compression method in flate stream") — a real version
 * incompatibility between those two specific libraries, unrelated to the
 * extractor under test. `pdfkit` doesn't hit it.
 */
function makePdf(text: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFKitDocument({ size: 'A4' });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    if (text.length > 0) doc.text(text);
    doc.end();
  });
}

async function makeDocx(paragraphs: string[]): Promise<Buffer> {
  const doc = new DocxDocument({
    sections: [{ children: paragraphs.map((p) => new Paragraph({ children: [new TextRun(p)] })) }],
  });
  return Packer.toBuffer(doc);
}

describe('extractPdfText — against a REAL PDF generated by pdfkit (proves real byte parsing, not a mock)', () => {
  it('extracts the exact text that was written into the PDF', async () => {
    const bytes = await makePdf('CareerPilot Resume Extraction Test');
    const result = await extractPdfText(bytes);
    expect(isOk(result)).toBe(true);
    if (isOk(result)) {
      expect(result.value).toContain('CareerPilot Resume Extraction Test');
    }
  });

  it('fails with a typed corrupt_file error on garbage bytes, not a crash', async () => {
    const result = await extractPdfText(Buffer.from('this is not a pdf at all'));
    expect(isErr(result)).toBe(true);
    if (isErr(result)) expect(result.error.code).toBe('corrupt_file');
  });

  it('fails with empty_content on a PDF with no text (empty content stream)', async () => {
    const bytes = await makePdf('');
    const result = await extractPdfText(bytes);
    expect(isErr(result)).toBe(true);
    if (isErr(result)) expect(result.error.code).toBe('empty_content');
  });
});

describe('extractDocxText — against a REAL generated DOCX (docx -> mammoth round trip)', () => {
  it('extracts the exact paragraphs that were written into the DOCX', async () => {
    const bytes = await makeDocx(['Jane Smith', 'jane.smith@example.com', 'Senior Software Engineer at Acme Corp']);
    const result = await extractDocxText(bytes);
    expect(isOk(result)).toBe(true);
    if (isOk(result)) {
      expect(result.value).toContain('Jane Smith');
      expect(result.value).toContain('jane.smith@example.com');
      expect(result.value).toContain('Senior Software Engineer at Acme Corp');
    }
  });

  it('fails with a typed corrupt_file error on garbage bytes, not a crash', async () => {
    const result = await extractDocxText(Buffer.from('this is not a docx at all'));
    expect(isErr(result)).toBe(true);
    if (isErr(result)) expect(result.error.code).toBe('corrupt_file');
  });

  it('fails with empty_content on a DOCX with no paragraphs', async () => {
    const bytes = await makeDocx([]);
    const result = await extractDocxText(bytes);
    expect(isErr(result)).toBe(true);
    if (isErr(result)) expect(result.error.code).toBe('empty_content');
  });
});

describe('DocumentTextExtractor — dispatch by mime type', () => {
  const extractor = new DocumentTextExtractor();

  it('routes application/pdf to the PDF extractor', async () => {
    const bytes = await makePdf('Dispatch Test PDF');
    const result = await extractor.extractText(bytes, PDF_MIME_TYPE);
    expect(isOk(result)).toBe(true);
    if (isOk(result)) expect(result.value.text).toContain('Dispatch Test PDF');
  });

  it('routes the DOCX mime type to the DOCX extractor', async () => {
    const bytes = await makeDocx(['Dispatch Test DOCX']);
    const result = await extractor.extractText(bytes, DOCX_MIME_TYPE);
    expect(isOk(result)).toBe(true);
    if (isOk(result)) expect(result.value.text).toContain('Dispatch Test DOCX');
  });

  it('rejects an unsupported mime type as a typed error, not a crash', async () => {
    const result = await extractor.extractText(Buffer.from('hello'), 'image/png');
    expect(isErr(result)).toBe(true);
    if (isErr(result)) expect(result.error.code).toBe('unsupported_mime_type');
  });
});
