'use client';

import { useState } from 'react';
import type { FlaggedClaimDto } from '@careerpilot/contracts';
import { Badge, Button, Alert } from '@careerpilot/ui';

/**
 * Task 041 — the claim -> fact mapping panel. Every entry in `claims` is,
 * by construction (task 040's `verify-claims/v1.md` — see that prompt's
 * mandatory-omission rule), UNSUPPORTED: the adversarial auditor could not
 * independently re-derive a fact for it. There is no "mapped fact" to show
 * for a flagged claim (if one existed, it wouldn't be flagged) — so this
 * panel's job is showing the claim text, its low confidence, and a per-
 * claim accept/reject decision, then one submit action for the whole
 * version (task 041's own scope: "accept/reject per claim... updates the
 * document version's review state").
 */
export function ClaimReviewPanel({
  claims, submitting, onSubmit,
}: {
  claims: readonly FlaggedClaimDto[];
  submitting: boolean;
  onSubmit: (approved: boolean) => void;
}) {
  const [decisions, setDecisions] = useState<Record<number, 'accept' | 'reject'>>({});

  const allDecided = claims.every((_, i) => decisions[i] !== undefined);
  const anyRejected = Object.values(decisions).includes('reject');

  return (
    <div className="flex flex-col gap-3">
      <Alert variant="warning">
        This version was generated by AI and {claims.length} claim{claims.length === 1 ? '' : 's'} could not be
        independently verified against your profile. Review each one before this document can be exported.
      </Alert>

      <ul className="flex flex-col gap-2">
        {claims.map((claim, i) => (
          <li key={i} className="rounded-md border border-neutral-200 p-3">
            <div className="mb-2 flex items-start justify-between gap-3">
              <p className="text-sm text-neutral-900">{claim.text}</p>
              <Badge variant="danger" className="shrink-0">UNSUPPORTED — needs your review</Badge>
            </div>
            <p className="mb-2 text-xs text-neutral-500">Confidence: {(claim.confidence * 100).toFixed(0)}%</p>
            <div className="flex gap-2">
              <Button
                size="sm"
                variant={decisions[i] === 'accept' ? 'primary' : 'outline'}
                onClick={() => setDecisions((d) => ({ ...d, [i]: 'accept' }))}
              >
                This is accurate
              </Button>
              <Button
                size="sm"
                variant={decisions[i] === 'reject' ? 'danger' : 'outline'}
                onClick={() => setDecisions((d) => ({ ...d, [i]: 'reject' }))}
              >
                This is wrong
              </Button>
            </div>
          </li>
        ))}
      </ul>

      <div className="flex items-center gap-3">
        <Button
          disabled={!allDecided || anyRejected || submitting}
          loading={submitting}
          onClick={() => onSubmit(true)}
        >
          Approve and unblock export
        </Button>
        {anyRejected && (
          <Button variant="outline" disabled={submitting} loading={submitting} onClick={() => onSubmit(false)}>
            Confirm rejection — keep blocked, regenerate instead
          </Button>
        )}
        {!allDecided && <span className="text-xs text-neutral-500">Decide on every claim to continue.</span>}
      </div>
    </div>
  );
}
